{
 "title": "Discography Stats",
 "description": "Discography",
 "time": { "from": "1959-01-01T00:00:00.000Z", "to": "2025-01-01T00:00:00.000Z" },
 "refresh": "1h",
 "panels": [
  {
   "title": "By Year DSD PCM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 0 },
   "targets": [
    { "dataset": "discography", "rawSql": "SELECT *\nFROM album_count\n\n" }
   ]
  },
  {
   "title": "By Size GB",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "dataset": "discography",
     "rawSql": "SELECT format, (SUM(size)/1024/1024/1024)::NUMERIC(6,1) as size_gb\nFROM albums\nGROUP BY format"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "discography",
     "rawSql": "SELECT SUM(size)/1024/1024/1024::NUMERIC(6,1) FROM albums"
    }
   ]
  },
  {
   "title": "By Year Smoothed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "discography",
     "rawSql": "SELECT year, \nAVG(dsf) OVER (\n        ORDER BY year \n        ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING\n    ) AS DSD,\nAVG(flac) OVER (\n        ORDER BY year \n        ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING\n    ) AS PCM,\nAVG(\"all\") OVER (\n        ORDER BY year \n        ROWS BETWEEN 5 PRECEDING AND 5 FOLLOWING\n    ) AS ALL\nFROM album_count "
    }
   ]
  },
  {
   "title": "By Album Count",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "discography",
     "rawSql": "SELECT format AS type, COUNT(*) AS albums\nFROM albums\nGROUP BY format\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Total Albums",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "discography", "rawSql": "SELECT COUNT(*) FROM albums" }
   ]
  }
 ]
}